# Build all the things
FROM node:18.17-bullseye-slim AS build
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
      build-essential \
      gcc autoconf \
      automake \
      zlib1g-dev \
      libpng-dev \
      nasm bash \
      libvips-dev \
    && apt-get clean

ENV NODE_ENV=production

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

WORKDIR /app

COPY config ./config
COPY database ./database
COPY public ./public
COPY src ./src

COPY .env \
     .nvmrc \
     .npmrc \
     favicon.png \
     package.json \
     pnpm-lock.yaml \
     entrypoint.sh \
     tsconfig.json \
     ./

RUN pnpm install --frozen-lockfile

RUN pnpm build

# Copy only the built files into the final image
FROM node:18.17-bullseye-slim AS runner
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y libvips-dev && \
    apt-get clean

ENV NODE_ENV=production

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 strapi

COPY --from=build --chown=strapi:nodejs /app ./

USER strapi

EXPOSE 1337
ENTRYPOINT ["/app/entrypoint.sh"]
